// <auto-generated />
using System;
using AspNetCoreWebApi6.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreWebApi6.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20230911222636_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNetCoreWebApi6.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SuperVisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 502030,
                            Code = "EMP320",
                            Name = "Mehedi Hasan",
                            Salary = 50000,
                            SuperVisorId = 502036
                        },
                        new
                        {
                            Id = 502031,
                            Code = "EMP321",
                            Name = "Ashikur Rahman",
                            Salary = 45000,
                            SuperVisorId = 502036
                        },
                        new
                        {
                            Id = 502032,
                            Code = "EMP322",
                            Name = "Rakibul Islam",
                            Salary = 52000,
                            SuperVisorId = 502030
                        },
                        new
                        {
                            Id = 502033,
                            Code = "EMP323",
                            Name = "Hasan Abdullah",
                            Salary = 46000,
                            SuperVisorId = 502031
                        },
                        new
                        {
                            Id = 502034,
                            Code = "EMP324",
                            Name = "Akib Khan",
                            Salary = 66000,
                            SuperVisorId = 502032
                        },
                        new
                        {
                            Id = 502035,
                            Code = "EMP325",
                            Name = "Rasel Shikder",
                            Salary = 53500,
                            SuperVisorId = 502033
                        },
                        new
                        {
                            Id = 502036,
                            Code = "EMP326",
                            Name = "Selim Reja",
                            Salary = 59000,
                            SuperVisorId = 502035
                        });
                });

            modelBuilder.Entity("AspNetCoreWebApi6.Entities.EmployeeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffday")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EmployeeAttendances");
                });
#pragma warning restore 612, 618
        }
    }
}
